import { OVERRIDE_MAP, THEMES } from "./prompts";

const OUT = "prototype/project/roguent/overrides.js";

/** 纯函数:产出注入原型的 overrides.js 文本。 */
export function renderOverridesJs(theme: string): string {
  const payload = { theme, map: OVERRIDE_MAP };
  return `/* AUTO-GENERATED by scripts/art/overrides.ts — do not edit by hand. */\nwindow.ART_OVERRIDE = ${JSON.stringify(payload, null, 2)};\n`;
}

async function main(): Promise<void> {
  const i = Bun.argv.indexOf("--theme");
  const theme = i >= 0 ? Bun.argv[i + 1] : "cyber";
  if (!theme || !THEMES.includes(theme as (typeof THEMES)[number])) {
    throw new Error(`--theme 必须是 ${THEMES.join(" / ")}`);
  }
  await Bun.write(OUT, renderOverridesJs(theme));
  console.log(`✓ ${OUT} (theme=${theme})`);
}

if (import.meta.main) {
  await main();
}
