// scripts/generate-verification-report.ts
// Discovers smoke artifacts + optional command-log inputs, builds a
// markdown verification report, and writes it to docs/verification/.
//
// Pure core: buildVerificationReport(inputs) → string  (no I/O, no Date.now)
// Thin main(): discovers files, stamps timestamp, calls core, writes file.

import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SmokeArtifact {
  target: string;
  mode: string;
  status: "passed" | "degraded" | "blocked";
  observedEvents: string[];
  blockers: Array<{ stage: string; reason: string }>;
  version?: string;
  notes?: string;
  ranAtMs: number;
}

export interface StaticCheckSummary {
  /** e.g. "biome check" */
  tool: string;
  /** "passed" | "failed" | "not-captured-this-run" */
  status: "passed" | "failed" | "not-captured-this-run";
  detail?: string;
}

export interface UnitTestSummary {
  /** "passed" | "failed" | "not-captured-this-run" */
  status: "passed" | "failed" | "not-captured-this-run";
  total?: number;
  passed?: number;
  failed?: number;
  skipped?: number;
  detail?: string;
}

export interface E2ESummary {
  /** "passed" | "failed" | "not-captured-this-run" */
  status: "passed" | "failed" | "not-captured-this-run";
  total?: number;
  passed?: number;
  failed?: number;
  skipped?: number;
  /** Short description of scope — e.g. "replay E2E (offline, zero-quota)" */
  scope?: string;
  detail?: string;
}

export interface ReportInputs {
  smokeArtifacts: SmokeArtifact[];
  staticChecks: StaticCheckSummary[];
  unitTest: UnitTestSummary;
  e2e: E2ESummary;
  /** ISO string, e.g. "2026-06-10T12:34:56.789Z" */
  generatedAt: string;
  /** Project slug shown in the report heading */
  projectSlug?: string;
}

// ---------------------------------------------------------------------------
// Pure core — no I/O, no Date.now
// ---------------------------------------------------------------------------

export function buildVerificationReport(inputs: ReportInputs): string {
  const {
    smokeArtifacts,
    staticChecks,
    unitTest,
    e2e,
    generatedAt,
    projectSlug = "roguent-full-prototype",
  } = inputs;

  const lines: string[] = [];

  // Header
  lines.push(`# Verification Report — ${projectSlug}`);
  lines.push(`Generated: ${generatedAt}`);
  lines.push("");
  lines.push(
    "> This report is auto-generated by `scripts/generate-verification-report.ts`.",
  );
  lines.push(
    "> It aggregates observed evidence only — sections marked **not-captured-this-run** were not",
  );
  lines.push(
    "> observed in this invocation and make no claims about pass/fail.",
  );
  lines.push("");
  lines.push("---");
  lines.push("");

  // -------------------------------------------------------------------------
  // 1. Static Checks (lint / format / typecheck / build)
  // -------------------------------------------------------------------------
  lines.push("## 1. Static Checks");
  lines.push("");

  const staticPassed = staticChecks.filter((c) => c.status === "passed").length;
  const staticFailed = staticChecks.filter((c) => c.status === "failed").length;
  const staticNotCaptured = staticChecks.filter(
    (c) => c.status === "not-captured-this-run",
  ).length;

  lines.push("| Tool | Status | Detail |");
  lines.push("| ---- | ------ | ------ |");
  for (const check of staticChecks) {
    const statusBadge =
      check.status === "passed"
        ? "PASSED"
        : check.status === "failed"
          ? "FAILED"
          : "not-captured-this-run";
    lines.push(
      `| \`${check.tool}\` | ${statusBadge} | ${check.detail ?? ""} |`,
    );
  }
  lines.push("");
  lines.push(
    `**Summary:** ${staticPassed} passed, ${staticFailed} failed, ${staticNotCaptured} not captured this run`,
  );
  lines.push("");

  // -------------------------------------------------------------------------
  // 2. Unit Tests
  // -------------------------------------------------------------------------
  lines.push("## 2. Unit Tests (`bun test`)");
  lines.push("");

  if (unitTest.status === "not-captured-this-run") {
    lines.push(
      "> **not-captured-this-run** — unit test output was not provided to this invocation.",
    );
    lines.push("> Run `bun test` and pass results to confirm counts.");
  } else {
    const badge = unitTest.status === "passed" ? "PASSED" : "FAILED";
    const counts: string[] = [];
    if (unitTest.total !== undefined) counts.push(`total: ${unitTest.total}`);
    if (unitTest.passed !== undefined)
      counts.push(`passed: ${unitTest.passed}`);
    if (unitTest.failed !== undefined)
      counts.push(`failed: ${unitTest.failed}`);
    if (unitTest.skipped !== undefined)
      counts.push(`skipped: ${unitTest.skipped}`);
    lines.push(`**Status:** ${badge}`);
    if (counts.length > 0) lines.push(`**Counts:** ${counts.join(" | ")}`);
    if (unitTest.detail) lines.push(`**Detail:** ${unitTest.detail}`);
  }
  lines.push("");

  // -------------------------------------------------------------------------
  // 3. Replay E2E (explicitly labelled: offline, no quota)
  // -------------------------------------------------------------------------
  lines.push("## 3. Replay E2E — Offline, Zero-Quota");
  lines.push("");
  lines.push(
    "> **Scope:** These tests run against pre-recorded fixtures replayed by the engine.",
  );
  lines.push(
    "> No real external API calls are made. No Claude subscription quota is consumed.",
  );
  lines.push(
    "> This section is DISTINCT from real external smoke tests (see Section 4).",
  );
  lines.push("");

  if (e2e.status === "not-captured-this-run") {
    lines.push(
      "> **not-captured-this-run** — E2E output was not provided to this invocation.",
    );
    lines.push(
      "> Run `bun run test:e2e -- --project=chromium` to capture results.",
    );
  } else {
    const badge = e2e.status === "passed" ? "PASSED" : "FAILED";
    const counts: string[] = [];
    if (e2e.total !== undefined) counts.push(`total: ${e2e.total}`);
    if (e2e.passed !== undefined) counts.push(`passed: ${e2e.passed}`);
    if (e2e.failed !== undefined) counts.push(`failed: ${e2e.failed}`);
    if (e2e.skipped !== undefined) counts.push(`skipped: ${e2e.skipped}`);
    lines.push(`**Status:** ${badge}`);
    if (counts.length > 0) lines.push(`**Counts:** ${counts.join(" | ")}`);
    if (e2e.scope) lines.push(`**Scope:** ${e2e.scope}`);
    if (e2e.detail) lines.push(`**Detail:** ${e2e.detail}`);
  }
  lines.push("");

  // -------------------------------------------------------------------------
  // 4. Real External Smoke Tests
  // -------------------------------------------------------------------------
  lines.push("## 4. Real External Smoke Tests");
  lines.push("");
  lines.push(
    "> **Scope:** Each entry below is a real integration smoke test against an external",
  );
  lines.push(
    "> service (or its closest available proxy). Status reflects the furthest stage",
  );
  lines.push(
    "> exercised, NOT a full end-to-end user flow unless explicitly noted.",
  );
  lines.push(
    "> **IMPORTANT:** A `passed` status with a real-API blocker means the local/offline",
  );
  lines.push(
    "> portion passed but the real external account flow was NOT exercised.",
  );
  lines.push("");

  if (smokeArtifacts.length === 0) {
    lines.push("> No smoke artifacts found.");
  } else {
    const smkPassed = smokeArtifacts.filter(
      (a) => a.status === "passed",
    ).length;
    const smkDegraded = smokeArtifacts.filter(
      (a) => a.status === "degraded",
    ).length;
    const smkBlocked = smokeArtifacts.filter(
      (a) => a.status === "blocked",
    ).length;

    lines.push(
      `**Summary:** ${smokeArtifacts.length} targets — ${smkPassed} passed (local/partial), ${smkDegraded} degraded, ${smkBlocked} blocked`,
    );
    lines.push("");

    for (const artifact of smokeArtifacts) {
      lines.push(
        `### 4.${smokeArtifacts.indexOf(artifact) + 1} \`${artifact.target}\``,
      );
      lines.push("");

      // Status with annotation for local-only "passed"
      const hasRealApiBlocker = artifact.blockers.some(
        (b) =>
          b.stage.includes("api") ||
          b.stage.includes("credentials") ||
          b.stage.includes("entitlement") ||
          b.stage.includes("config"),
      );

      let statusLabel: string;
      if (artifact.status === "passed" && hasRealApiBlocker) {
        statusLabel =
          "PASSED (local/partial — real external API NOT exercised; see blocker below)";
      } else if (artifact.status === "passed") {
        statusLabel = "PASSED";
      } else if (artifact.status === "degraded") {
        statusLabel = "DEGRADED";
      } else {
        statusLabel = "BLOCKED";
      }

      lines.push("| Field | Value |");
      lines.push("| ----- | ----- |");
      lines.push(`| **Status** | ${statusLabel} |`);
      lines.push(`| **Mode** | \`${artifact.mode}\` |`);
      lines.push(
        `| **Ran at** | ${new Date(artifact.ranAtMs).toISOString()} |`,
      );
      if (artifact.version) lines.push(`| **Version** | ${artifact.version} |`);
      lines.push("");

      if (artifact.observedEvents.length > 0) {
        lines.push(
          `**Observed events:** ${artifact.observedEvents.map((e) => `\`${e}\``).join(", ")}`,
        );
        lines.push("");
      }

      if (artifact.blockers.length > 0) {
        lines.push("**Blockers:**");
        lines.push("");
        for (const blocker of artifact.blockers) {
          lines.push(`- **Stage \`${blocker.stage}\`:** ${blocker.reason}`);
        }
        lines.push("");
      }

      if (artifact.notes) {
        lines.push(`**Notes:** ${artifact.notes}`);
        lines.push("");
      }
    }
  }

  // -------------------------------------------------------------------------
  // 5. Unverified / Blockers Summary
  // -------------------------------------------------------------------------
  lines.push("## 5. Unverified / Blockers Summary");
  lines.push("");

  const allBlockers: Array<{
    source: string;
    stage: string;
    reason: string;
  }> = [];

  for (const artifact of smokeArtifacts) {
    for (const blocker of artifact.blockers) {
      allBlockers.push({
        source: artifact.target,
        stage: blocker.stage,
        reason: blocker.reason,
      });
    }
  }

  const failedStatic = staticChecks.filter((c) => c.status === "failed");
  const notCaptured: string[] = [];
  if (unitTest.status === "not-captured-this-run")
    notCaptured.push("unit tests");
  if (e2e.status === "not-captured-this-run") notCaptured.push("replay E2E");
  for (const check of staticChecks) {
    if (check.status === "not-captured-this-run")
      notCaptured.push(`static: ${check.tool}`);
  }

  if (
    allBlockers.length === 0 &&
    failedStatic.length === 0 &&
    notCaptured.length === 0
  ) {
    lines.push("> No blockers or unverified items.");
  } else {
    if (failedStatic.length > 0) {
      lines.push("### Failed Static Checks");
      lines.push("");
      for (const check of failedStatic) {
        lines.push(`- **${check.tool}:** ${check.detail ?? "failed"}`);
      }
      lines.push("");
    }

    if (allBlockers.length > 0) {
      lines.push("### External Smoke Blockers");
      lines.push("");
      lines.push("| Target | Stage | Reason |");
      lines.push("| ------ | ----- | ------ |");
      for (const b of allBlockers) {
        lines.push(`| \`${b.source}\` | \`${b.stage}\` | ${b.reason} |`);
      }
      lines.push("");
    }

    if (notCaptured.length > 0) {
      lines.push("### Not Captured This Run");
      lines.push("");
      lines.push(
        "The following were not observed in this report invocation — results are unknown:",
      );
      lines.push("");
      for (const item of notCaptured) {
        lines.push(`- ${item}`);
      }
      lines.push("");
      lines.push(
        "> Re-run with command-log inputs provided, or run the checks independently.",
      );
    }
  }

  lines.push("");
  lines.push("---");
  lines.push(
    "*Report generated by `scripts/generate-verification-report.ts`. Evidence only — no claims are made beyond what was observed.*",
  );

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// main() — I/O wrapper, uses Date.now()
// ---------------------------------------------------------------------------

async function main() {
  const projectRoot = new URL("..", import.meta.url).pathname.replace(
    /\/$/,
    "",
  );
  const artifactsDir = join(projectRoot, "tests/e2e/artifacts");
  const outDir = join(projectRoot, "docs/verification");

  // Discover smoke artifacts
  const smokeArtifacts: SmokeArtifact[] = [];
  try {
    const entries = await readdir(artifactsDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory() || !entry.name.endsWith("-smoke")) continue;
      const resultPath = join(artifactsDir, entry.name, "result.json");
      try {
        const raw = await readFile(resultPath, "utf-8");
        smokeArtifacts.push(JSON.parse(raw) as SmokeArtifact);
      } catch {
        console.warn(`[verify:report] Could not read ${resultPath} — skipped`);
      }
    }
  } catch {
    console.warn(
      `[verify:report] Could not read artifacts dir ${artifactsDir} — no smoke artifacts`,
    );
  }

  // Sort by target name for stable output
  smokeArtifacts.sort((a, b) => a.target.localeCompare(b.target));

  // Static checks — not-captured-this-run unless env vars say otherwise
  // We could accept JSON via args/env; for now emit placeholders.
  const staticChecks: StaticCheckSummary[] = [
    { tool: "bun run check (biome)", status: "not-captured-this-run" },
    { tool: "bunx tsc --noEmit", status: "not-captured-this-run" },
    { tool: "bun run typecheck:e2e", status: "not-captured-this-run" },
    { tool: "bun run build", status: "not-captured-this-run" },
  ];

  // Check for env-var overrides: VERIFY_STATIC_JSON=<JSON array of StaticCheckSummary>
  const staticEnv = process.env.VERIFY_STATIC_JSON;
  if (staticEnv) {
    try {
      const parsed = JSON.parse(staticEnv) as StaticCheckSummary[];
      staticChecks.splice(0, staticChecks.length, ...parsed);
    } catch {
      console.warn(
        "[verify:report] VERIFY_STATIC_JSON is not valid JSON — ignored",
      );
    }
  }

  // Unit test summary — not-captured-this-run unless env var provided
  let unitTest: UnitTestSummary = { status: "not-captured-this-run" };
  const unitEnv = process.env.VERIFY_UNIT_JSON;
  if (unitEnv) {
    try {
      unitTest = JSON.parse(unitEnv) as UnitTestSummary;
    } catch {
      console.warn(
        "[verify:report] VERIFY_UNIT_JSON is not valid JSON — ignored",
      );
    }
  }

  // E2E summary — not-captured-this-run unless env var provided
  let e2e: E2ESummary = { status: "not-captured-this-run" };
  const e2eEnv = process.env.VERIFY_E2E_JSON;
  if (e2eEnv) {
    try {
      e2e = JSON.parse(e2eEnv) as E2ESummary;
    } catch {
      console.warn(
        "[verify:report] VERIFY_E2E_JSON is not valid JSON — ignored",
      );
    }
  }

  const now = new Date();
  const generatedAt = now.toISOString();
  // Filesystem-safe timestamp: replace : with -
  const fsTimestamp = generatedAt.replace(/:/g, "-").replace(/\.\d+Z$/, "Z");

  const report = buildVerificationReport({
    smokeArtifacts,
    staticChecks,
    unitTest,
    e2e,
    generatedAt,
    projectSlug: "roguent-full-prototype",
  });

  await mkdir(outDir, { recursive: true });
  const outFile = join(outDir, `${fsTimestamp}-roguent-full-prototype.md`);
  await writeFile(outFile, report, "utf-8");
  console.log(`[verify:report] Written → ${outFile}`);
  console.log(
    `[verify:report] ${smokeArtifacts.length} smoke artifacts included`,
  );
}

await main();
