import { OVERRIDE_MAP, THEMES } from "./prompts";

const OUT = "prototype/project/roguent/overrides.js";
const OVERRIDE_ANIMATIONS = {
  knight_m: {
    run: {
      prefix: "knight_m_run_f",
      count: 8,
      fps: 12,
    },
  },
} as const;

function assertTheme(
  theme: string | undefined,
): asserts theme is (typeof THEMES)[number] {
  if (!theme || !THEMES.includes(theme as (typeof THEMES)[number])) {
    throw new Error(`--theme 必须是 ${THEMES.join(" / ")}`);
  }
}

/** 纯函数:产出注入原型的 overrides.js 文本。 */
export function renderOverridesJs(theme: string | undefined): string {
  assertTheme(theme);
  const payload = { theme, map: OVERRIDE_MAP, animations: OVERRIDE_ANIMATIONS };
  return `/* AUTO-GENERATED by scripts/art/overrides.ts — do not edit by hand. */\nwindow.ART_OVERRIDE = ${JSON.stringify(payload, null, 2)};\n`;
}

async function main(): Promise<void> {
  const i = Bun.argv.indexOf("--theme");
  const theme = i >= 0 ? Bun.argv[i + 1] : "cyber";
  await Bun.write(OUT, renderOverridesJs(theme));
  console.log(`✓ ${OUT} (theme=${theme})`);
}

if (import.meta.main) {
  await main();
}
